services:
  - type: web
    name: number-game-backend
    env: java
    plan: free
    rootDir: Task1-NumberGame/backend
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar