package com.eduvault.api.service;

import java.util.Arrays;
import java.util.List;

public class PlacementInsightDatabase {

    public static final List<String> STRENGTHS = Arrays.asList(
        "Consistent Academic Excellence",
        "Strong Core Engineering Foundation",
        "Demonstrated Academic Progression",
        "Outstanding Technical Project Depth",
        "Versatile Full-Stack Skillset",
        "Advanced Problem Solving Skills",
        "Professional Web Portfolio Presence",
        "Diverse Technology Stack Competency",
        "Proven Hands-on Practical Expertise",
        "Dedicated Industry Certification Record",
        "Active Competitive Programming Profile",
        "Strong Collaboration & Team Leadership",
        "Exceptional Academic Discipline",
        "Industry-Standard Coding Standards",
        "Cloud Computing Familiarity",
        "Database Architecture Understanding",
        "Solid DevOps and Deployment Baseline",
        "Mobile Application Development Competency",
        "Data Analytics and Visualization Skill",
        "AI and Machine Learning Knowledge",
        "Continuous Learning Orientation",
        "Effective Technical Documentation Habit",
        "Well-Rounded Co-Curricular Profile",
        "Rapid Prototyping Capability",
        "System Design Concepts Familiarity",
        "API Development and Integration Mastery",
        "Robust Software Testing Awareness",
        "Active Professional Networking Presence",
        "Open Source Contributor Mindset",
        "Agile Methodology Comprehension",
        "Strong Security Best Practices Awareness",
        "Exceptional Attendance Consistency"
    );

    public static final List<String> WEAKNESSES = Arrays.asList(
        "Academic performance needs enhancement",
        "Critical classroom attendance shortage",
        "Absence of hands-on project exposure",
        "Limited practical project diversity",
        "Narrow technical skill profile",
        "Lack of industry-recognized certifications",
        "No co-curricular or competitive achievements",
        "Missing professional portfolio website",
        "Weak professional brand visibility",
        "Limited open-source/GitHub activity proof",
        "Insufficient database management experience",
        "Lack of cloud platform exposure",
        "Inconsistent academic performance trend",
        "Low profile completion rate",
        "Minimal DevOps or deployment familiarity",
        "Weak foundational programming language depth",
        "Limited exposure to software testing practices",
        "Inadequate project description detail",
        "Lack of collaborative team project experience",
        "No hackathon or coding competition participation",
        "Absence of specialized technical focus",
        "Limited web development framework expertise",
        "Lack of RESTful API development knowledge",
        "Minimal system design exposure",
        "No experience with version control systems",
        "Unfamiliarity with Agile development practices",
        "Lack of UI/UX design awareness",
        "Limited data structures and algorithms exposure",
        "Incomplete semester history record",
        "Lack of research or technical writing experience",
        "Minimal exposure to asynchronous programming",
        "Missing career status definition"
    );

    public static final List<String> RECOMMENDATIONS = Arrays.asList(
        "Build production-grade full-stack applications",
        "Complete cloud computing certifications (AWS/GCP)",
        "Solve 150+ Data Structures & Algorithms problems",
        "Participate in local and national hackathons",
        "Contribute to open-source GitHub repositories",
        "Deploy your existing projects to Vercel/Netlify/Render",
        "Obtain a database management system certification",
        "Create a comprehensive readme for all GitHub projects",
        "Optimize your LinkedIn profile for technical recruiters",
        "Earn a professional Scrum Master or Agile certificate",
        "Develop an AI/ML project using real-world datasets",
        "Build a microservices-based backend application",
        "Implement unit testing in your current projects",
        "Publish a technical blog post on Medium or Dev.to",
        "Practice mock interviews on Pramp or Interviewing.io",
        "Participate in competitive programming on LeetCode/Codeforces",
        "Learn containerization tools like Docker and Kubernetes",
        "Build an API gateway or custom integration service",
        "Improve classroom attendance to exceed 80% threshold",
        "Add details to academic achievements and honors",
        "Develop a mobile app using Flutter or React Native",
        "Strengthen OOP and SOLID design pattern knowledge",
        "Learn CI/CD pipeline configuration using GitHub Actions",
        "Collaborate on a group project with peer developers",
        "Obtain a security or ethical hacking foundation certificate",
        "Create a video demo for your top portfolio projects",
        "Learn modern CSS frameworks like TailwindCSS",
        "Attend industry webinars and networking events",
        "Apply for internships to gain real-world industry experience",
        "Establish a daily coding routine on GitHub",
        "Master version control and advanced Git branching",
        "Prepare a strong, clean one-page resume"
    );

    public static final List<String> PLACEMENT_INSIGHTS = Arrays.asList(
        "Highly competitive candidate for top-tier software companies",
        "Strong fit for development and system engineering roles",
        "Good potential for full-stack web developer positions",
        "Excellent candidate for cloud associate or DevOps engineer paths",
        "Strong candidate for data analyst and business intelligence roles",
        "Well-positioned for AI/ML engineering trainee positions",
        "Excellent fit for technical consultant and client-facing roles",
        "A strong candidate for mobile developer internships",
        "Developing candidate with high potential in backend roles",
        "Candidate needs to bridge skill gaps before active hiring seasons",
        "Urgent improvement in projects needed to secure interviews",
        "Academic records are a major strength; highlight in resume screening",
        "Low attendance may flag reliability concerns with recruiters",
        "Strong portfolio presence will increase recruiter response rate",
        "Needs to highlight certification achievements to stand out",
        "Competitive coding credentials will open doors to elite tech firms",
        "Tech stack diversity indicates high adaptability in agile teams",
        "Excellent consistency in academic grades suggests high learnability",
        "Lack of team projects could raise questions about collaboration skills",
        "Good foundation, but needs to work on coding test speed",
        "Needs to establish clear specialization (Frontend/Backend/Data)",
        "Highly recommended for fast-track product engineering roles",
        "Target early-stage startups for broad engineering exposure",
        "Excellent communication and documentation skills are highlighted",
        "Highly suitable for QA engineering and automation testing roles",
        "Focus on medium-scale enterprises for stable career entry",
        "Profile exhibits strong potential for research & development roles",
        "Active LinkedIn presence makes you discoverable by headhunters",
        "GitHub green graph represents consistent developer commitment",
        "High CGPA makes you eligible for premium consulting firms",
        "Demonstrated growth curve is highly valued by hiring managers",
        "Requires immediate focus on foundational programming languages"
    );

    public static final List<String> CAREER_GROWTH = Arrays.asList(
        "Pursue a specialized path in Cloud Architecture (AWS/Azure)",
        "Transition from simple coding to Advanced System Design",
        "Aim for Tech Lead responsibilities in collaborative projects",
        "Establish expertise in Decentralized Applications (Web3)",
        "Deep dive into DevOps Engineering and Infrastructure as Code",
        "Master Advanced Machine Learning and Neural Networks",
        "Develop expertise in Data Engineering and ETL Pipelines",
        "Focus on Cybersecurity, Penetration Testing, or DevSecOps",
        "Cultivate Product Management skills alongside technical depth",
        "Transition towards Mobile Dev leadership using Flutter/Swift",
        "Invest time in learning Big Data systems (Spark/Hadoop)",
        "Learn low-level programming (C/Rust) for systems engineering",
        "Build an audience by contributing to open-source frameworks",
        "Develop micro-SaaS applications to understand business logic",
        "Prepare for graduate studies or research-oriented career paths",
        "Aim for roles in high-frequency trading or quantitative analysis",
        "Master modern UI/UX design paradigms to complement frontend engineering",
        "Focus on Enterprise Application Integration using Spring/Java",
        "Develop expert-level proficiency in SQL and Query Optimization",
        "Learn functional programming concepts (Scala/Haskell)",
        "Build skills in Embedded Systems and Internet of Things (IoT)",
        "Specialize in Data Privacy, Compliance, and Governance",
        "Aim for Technical Product Owner roles in scrum teams",
        "Master cross-platform desktop application dev (Electron/Tauri)",
        "Explore AR/VR development using Unity or Unreal Engine",
        "Develop skills in Robotic Process Automation (RPA)",
        "Master Game Development fundamentals and physics engines",
        "Deepen understanding of compiler design and custom parsers",
        "Specialize in Geographic Information Systems (GIS) dev",
        "Transition to Site Reliability Engineering (SRE) practices",
        "Master Serverless application architectures and microservices",
        "Explore bio-informatics and computational biology careers"
    );

    public static final List<String> LEARNING_SUGGESTIONS = Arrays.asList(
        "Take an advanced course on Data Structures & Algorithms",
        "Study microservices architecture and API gateway routing",
        "Complete a course on Docker containerization basics",
        "Study SQL database design and query execution planning",
        "Learn modern JavaScript frameworks (React 19 / NextJS 15)",
        "Take a comprehensive course on Spring Boot backend dev",
        "Study Linux command line and Shell Scripting automation",
        "Learn Python for Data Science and Machine Learning",
        "Study clean code principles and SOLID design patterns",
        "Learn Git version control and collaborative workflows",
        "Take an introductory course on Cloud Computing (AWS/GCP)",
        "Study computer networking fundamentals (TCP/IP, HTTP)",
        "Learn NoSQL database concepts and MongoDB integration",
        "Take a course on HTML5, CSS3, and Responsive Web Design",
        "Study software testing methodologies (Unit, Integration, E2E)",
        "Learn TypeScript to write type-safe scalable applications",
        "Study compiler design or programming language theory",
        "Learn REST API design principles and OpenAPI documentation",
        "Take a course on UI/UX design tools (Figma, Adobe XD)",
        "Learn server-side rendering and static site generation",
        "Study operating systems internals and memory management",
        "Learn mobile development basics (React Native/Flutter)",
        "Study Scrum and Agile project management frameworks",
        "Learn about cryptography and modern security protocols",
        "Study GraphQL API design and query optimization",
        "Learn CSS preprocessing and Tailwind utility styling",
        "Study functional programming in JavaScript/Python",
        "Learn Node.js and asynchronous runtime concepts",
        "Take a course on Big Data architectures and pipelines",
        "Study Web Security vulnerabilities (OWASP Top 10)",
        "Learn test-driven development (TDD) methodologies",
        "Study message brokers like Apache Kafka and RabbitMQ"
    );

    public static final List<String> PROJECT_RECOMMENDATIONS = Arrays.asList(
        "Develop a real-time collaborative whiteboard application",
        "Build a microservices-based e-commerce backend platform",
        "Create a personal finance dashboard with data visualization",
        "Develop an AI-powered resume screening and scoring system",
        "Build a containerized chat application using WebSockets",
        "Create a custom compiler or interpreter in Java/Go",
        "Develop a distributed key-value store database from scratch",
        "Build a CI/CD pipeline automation dashboard",
        "Create a smart home IoT monitoring mobile application",
        "Develop a decentralized voting app on Ethereum testnet",
        "Build a secure password manager with local cryptography",
        "Create an analytics tool for tracking website user behavior",
        "Develop a multiplayer web game using canvas and sockets",
        "Build a customized content management system (CMS)",
        "Create a weather forecasting application using public APIs",
        "Develop a bug tracking and team collaboration board",
        "Build a recipe discovery engine with AI suggestions",
        "Create a markdown editor with live HTML preview",
        "Develop a stock market portfolio tracker with notifications",
        "Build a library management system with QR code scans",
        "Create an audio streaming platform with custom player",
        "Develop a fitness tracking application with charts",
        "Build an automated email marketing scheduler",
        "Create a real-time server monitoring dashboard",
        "Develop a hotel room booking and billing system",
        "Build a web-based code editor with syntax compile",
        "Create a URL shortener with analytics and QR code",
        "Develop a geo-location tracking delivery manager",
        "Build a customer feedback sentiment analysis tool",
        "Create a task manager with drag-and-drop board",
        "Develop a file sharing service with secure temp links",
        "Build a social media analytics dashboard"
    );

    public static final List<String> CERTIFICATION_RECOMMENDATIONS = Arrays.asList(
        "AWS Certified Cloud Practitioner",
        "Oracle Certified Associate: Java SE Programmer",
        "Google Cloud Associate Cloud Engineer",
        "Microsoft Certified: Azure Fundamentals",
        "Certified ScrumMaster (CSM)",
        "Cisco Certified Network Associate (CCNA)",
        "CompTIA Security+",
        "HashiCorp Certified: Terraform Associate",
        "Docker Certified Associate (DCA)",
        "MongoDB Certified Developer Associate",
        "Salesforce Certified Administrator",
        "FreeCodeCamp Responsive Web Design Certification",
        "Meta Front-End Developer Professional Certificate",
        "Google Data Analytics Professional Certificate",
        "IBM Applied AI Professional Certificate",
        "Stanford Online Algorithms Specialization",
        "FreeCodeCamp JavaScript Algorithms and Data Structures",
        "Postman API Student Expert Certification",
        "Udacity Full Stack Web Developer Nanodegree",
        "HackerRank Problem Solving (Problem Solving Basic/Intermediate)",
        "Certified Kubernetes Administrator (CKA)",
        "AWS Certified Solutions Architect – Associate",
        "Meta Back-End Developer Professional Certificate",
        "Google IT Support Professional Certificate",
        "DeepLearning.AI Machine Learning Specialization",
        "CompTIA Network+",
        "Certified Ethical Hacker (CEH)",
        "Spring Certified Professional",
        "Professional Scrum Master I (PSM I)",
        "Elastic Certified Engineer",
        "Palo Alto Networks Certified Cybersecurity Associate",
        "Google Project Management Professional Certificate"
    );
}
