package com.eduvault.api.service;

import java.util.Arrays;
import java.util.List;

public class RiskInsightDatabase {

    public static final List<String> RISK_REASONS = Arrays.asList(
        "Academic decline detected across recent semesters",
        "Attendance trend below expected threshold",
        "Limited project experience",
        "Low portfolio completion",
        "Insufficient industry-relevant skills",
        "Certificate coverage below peer average",
        "Weak practical exposure",
        "Lack of learning progression",
        "Critical decline in SGPA from previous terms",
        "Attendance dropped below 75% class warning level",
        "Zero published projects found in repository profile",
        "No active professional portfolio published to date",
        "Missing essential core tech skills (DSA, SQL, etc.)",
        "No verified industry certifications on file",
        "Low overall CGPA representing severe academic drift",
        "Zero recent profile activity or project updates logged",
        "Lack of participation in extra-curricular hackathons",
        "Missing links for LinkedIn or GitHub validation profiles",
        "Repeated negative slope in SGPA performance curves",
        "Extremely sparse semester records indicating engagement gap",
        "Insufficient programming depth or diversity markers",
        "No verifiable project description or readme files",
        "Below threshold grades in core foundational classes",
        "Incomplete academic profile configuration setup",
        "Attendance warning level registered in multiple sections",
        "Placement readiness index significantly below average",
        "No registered student achievements or awards recorded",
        "Failure to submit semester performance records",
        "Inadequate learning consistency and progress markers",
        "Lack of technology relevance updates in selected stack",
        "Weak academic growth index over the current calendar year",
        "Zero mock placement test attempts or preparation logs"
    );

    public static final List<String> INTERVENTION_SUGGESTIONS = Arrays.asList(
        "Improve attendance consistency",
        "Complete one industry project",
        "Add cloud certification",
        "Improve DSA proficiency",
        "Strengthen portfolio quality",
        "Participate in hackathons",
        "Improve GitHub activity",
        "Build deployment-ready applications",
        "Strengthen communication skills",
        "Schedule mandatory academic advising meetings",
        "Join peer tutoring workshops for critical courses",
        "Register for core technology bootcamps on weekends",
        "Complete practice mock placement interview sessions",
        "Attend resume review workshops at career cells",
        "Participate in library study group circles daily",
        "Obtain faculty mentor endorsement for projects",
        "Enroll in foundational mathematics refresher courses",
        "Register for competitive coding challenge series",
        "Attend communication skill developmental seminars",
        "Sign up for department career path guidance panels",
        "Enroll in database systems specialized labs",
        "Register for software engineering methodology courses",
        "Attend local tech developer meetups and network",
        "Join student research project groups under faculty",
        "Obtain reference materials for lagging courses",
        "Enroll in full-stack engineering capstone tracks",
        "Complete structured placement readiness questionnaires",
        "Schedule bi-weekly SGPA tracking reviews",
        "Register with student success registry for support",
        "Enroll in system design and architecture workshops",
        "Attend professional profile polishing clinics",
        "Participate in mock tech test sessions weekly"
    );

    public static final List<String> IMPROVEMENT_ACTIONS = Arrays.asList(
        "Solve 50+ DSA problems on LeetCode or HackerRank",
        "Create 1 industry-ready project with documentation",
        "Configure GitHub actions CI/CD on active repository",
        "Publish professional portfolio to Vercel or Netlify",
        "Acquire cloud computing certificate (AWS/Azure/GCP)",
        "Write comprehensive README file for major projects",
        "Add Linkedin profile URL to portal student fields",
        "Resolve all warnings in pending Java/TypeScript code",
        "Complete 3 full-stack deployment tasks in sandbox",
        "Implement unit tests for core backend microservices",
        "Earn beginner badges on competitive coding sites",
        "Submit 2 pull requests to open source repositories",
        "Write 1 tech blog post about current learning project",
        "Participate in 1 department-level hackathon sprint",
        "Create system architecture diagram for portfolio showcase",
        "Complete 5 SQL query practice modules on platforms",
        "Review 3 peer project code repositories for feedback",
        "Containerize project applications using Docker build files",
        "Add API documentation using Swagger or Postman collections",
        "Update project description with accurate tech stack details",
        "Create mock database schema design for dynamic application",
        "Attend 2 developer webinars on backend microservices",
        "Complete 3 frontend CSS animations responsive tasks",
        "Implement basic auth and security headers on sandbox API",
        "Present project to department committee for feedback",
        "Optimize SQL queries on portfolio DB configurations",
        "Add unit test coverage report link to portfolio description",
        "Translate legacy project backend into modern Java Spring Boot",
        "Configure SSL certificates on custom portfolio deployments",
        "Publish npm package or library for open utility functions",
        "Build multi-tenant SaaS prototype application as project",
        "Register and participate in Google Hash Code challenges"
    );

    public static final List<String> ACADEMIC_RECOMMENDATIONS = Arrays.asList(
        "Implement strict study schedules of 3 hours daily",
        "Review SGPA monitoring logs weekly with class teacher",
        "Attend professor office hours for subject doubts",
        "Form library-based study groups with high performers",
        "Solve 5 previous year question papers before exam",
        "Register for remedial coaching classes in department",
        "Request secondary practice question sets from faculty",
        "Read reference textbook chapters on system concepts",
        "Participate in department subject discussion forums",
        "Write down key formulas and derivations in notebook",
        "Maintain detailed lecture notes for all active classes",
        "Set micro-goals for weekly assignment submissions",
        "Avoid missing consecutive classes in core modules",
        "Utilize online visual learning platforms for algorithms",
        "Request peer code review for programming lab works",
        "Draft concept maps for complex theory subjects",
        "Attempt quiz revisions on student portal daily",
        "Create flashcards for specialized terminology terms",
        "Schedule focus blocks using Pomodoro technique daily",
        "Practice database query writing on whiteboards weekly",
        "Take practice exam under simulated timed conditions",
        "Request model answer keys from previous class toppers",
        "Review class syllabus to track learning checkpoints",
        "Consult faculty advisor regarding backlog clearing plan",
        "Formulate step-by-step resolution guides for assignments",
        "Create quick-reference sheets for programming syntax",
        "Join math and statistics interest groups in campus",
        "Consult library resources for specialized database journals",
        "Document step-by-step derivations for core algorithms",
        "Review feedback logs on graded lab tasks immediately",
        "Participate in coding labs extra practice hours",
        "Set up study buddy system with departmental peer"
    );
}
