package com.eduvault.api.service;

import java.util.Arrays;
import java.util.List;

public class RoadmapDatabase {

    private RoadmapDatabase() {}

    public static final List<String> ACTIONS = Arrays.asList(
        "Complete 50+ programming problems on competitive platforms",
        "Implement a fully responsive design for a portfolio project",
        "Configure custom domain and SSL on portfolio page",
        "Write unit tests to achieve 80% coverage on core services",
        "Optimize SQL query performance using appropriate indexing",
        "Set up standard CI/CD pipeline using GitHub Actions",
        "Containerize microservices using Docker files",
        "Create structured API documentation with Swagger/Postman",
        "Deploy a Node/Spring Boot application to cloud environment",
        "Participate in a 24-hour hackathon or developer sprint",
        "Submit at least two pull requests to open source repositories",
        "Design and construct a relational database schema from scratch",
        "Add comprehensive README and architecture diagram to GitHub repository",
        "Configure system logging and trace tools in backend project",
        "Integrate OAuth2/JWT security validation in API gateway",
        "Implement cache layer using Redis or memory cache blocks",
        "Build a reusable frontend component library in React/Vue",
        "Create a state-driven dynamic dashboard interface",
        "Perform web accessibility checks on layout designs",
        "Optimize images and assets for performance improvement",
        "Implement real-time features using WebSockets or SSE",
        "Build a serverless function to automate background emails",
        "Perform regression and load testing on backend APIs",
        "Design a custom theme and layout styling guide",
        "Configure analytics trackers on deployed web projects",
        "Create a responsive email template for newsletter signups",
        "Conduct a peer code review session on team projects",
        "Configure environment variables securely in production",
        "Write clean, modular code following SOLID principles",
        "Implement lazy loading and code splitting in frontend assets",
        "Set up centralized error logging and alert mechanisms",
        "Design a multi-tenant data isolation strategy",
        "Implement internationalization (i18n) translation support",
        "Optimize database connections using HikariCP properties",
        "Create a custom Webpack/Vite build config configuration",
        "Implement file upload features using cloud storage integration",
        "Design a rate limiter for API endpoints to prevent abuse",
        "Write dynamic database migration scripts using Flyway/Liquibase",
        "Implement structured telemetry and metrics collection",
        "Configure proper CORS rules for multiple subdomains",
        "Create a mockup design using Figma before coding frontend",
        "Draft a robust system recovery and backup strategy",
        "Implement automated UI tests using Selenium/Playwright",
        "Refactor legacy codebase to reduce cognitive complexity",
        "Integrate payment gateway API endpoints securely",
        "Build an offline-first service worker sync for web apps",
        "Optimize CSS build sizes by stripping unused styling",
        "Integrate search indexing tools like Elasticsearch/Lucene",
        "Create an architectural decision record (ADR) log",
        "Perform security scanning using OWASP dependency check",
        "Implement automated database index tuning routine",
        "Conduct a detailed system performance audit session"
    );

    public static final List<String> SUGGESTIONS = Arrays.asList(
        "Improve lecture attendance consistency to build core knowledge",
        "Join a peer study group for complex algorithms revision",
        "Register for remedial training sessions run by departments",
        "Request secondary practice tasks from professors regularly",
        "Maintain clean subject binders and lecture summaries daily",
        "Formulate step-by-step notes for difficult theories",
        "Solve last 5 years' final exam papers before dates",
        "Schedule regular focus periods using Pomodoro technique",
        "Review graded assignment feedback logs immediately",
        "Consult faculty advisors to draft backlog resolution plans",
        "Attend laboratory practice hours during free slots",
        "Establish a daily coding routine of at least one hour",
        "Participate in online discussions on StackOverflow/Reddit",
        "Review conceptual gaps in linear algebra and statistics",
        "Draft visual concept maps for complex architecture tasks",
        "Create quick-reference sheets for language-specific syntax",
        "Attend technical webinars to learn modern methodologies",
        "Use active recall techniques during study reviews",
        "Track weekly study milestones using checklist systems",
        "Prepare mock exams under simulated class limits",
        "Collaborate on campus open source projects with peers",
        "Request model answers from course top performers",
        "Form a coding club in the department for mutual learning",
        "Engage with mentors to clear conceptual roadblocks",
        "Document step-by-step derivations for core formulas",
        "Revise basic data structures weekly to strengthen foundations",
        "Set up study buddy systems with class peers",
        "Seek tutoring support for challenging core modules",
        "Analyze past failures to pinpoint target improvement areas",
        "Improve verbal communication during technical presentations",
        "Participate in mock HR interview practice programs",
        "Attend industry talks organized by campus cells",
        "Draft clear elevator pitches for project presentations",
        "Organize peer mock reviews of technical resumes",
        "Refine explanations of project architectural decisions",
        "Practice whiteboarding algorithms under time limits",
        "Improve body language during mock interview rounds",
        "Prepare structured responses using the STAR method",
        "Analyze industry job postings to identify required competencies",
        "Seek constructive feedback on public speaking skills",
        "Watch recordings of system design mock interviews",
        "Draft professional cover letters tailored for internships",
        "Read articles on software engineering industry trends",
        "Attend local tech community meetups for networking",
        "Subscribe to technical newsletters for regular updates",
        "Practice writing clean documentation for minor utilities",
        "Familiarize yourself with agile and scrum methodologies",
        "Create simple slides to demonstrate complex designs",
        "Contribute comments and documentation to peer projects",
        "Participate in local department programming contests",
        "Schedule mock design sessions to practice architecture",
        "Verify theoretical concepts using small sandbox scripts"
    );

    public static final List<String> LEARNING = Arrays.asList(
        "Master Java Collections API and stream programming operations",
        "Learn core design patterns and SOLID coding concepts",
        "Understand relational database design and normalization theory",
        "Learn advanced JavaScript ES6+ features and async programming",
        "Master basic concepts of TypeScript and static typing systems",
        "Learn Spring Boot fundamentals, dependency injection, and JPA",
        "Understand MVC design and REST API structural principles",
        "Learn basic Git commands, branching models, and merge tactics",
        "Master CSS flexbox, grid layouts, and custom animations",
        "Learn state management patterns using Redux/Context APIs",
        "Understand security concepts like HTTPS, CORS, and SQL Injection",
        "Learn foundational Data Structures (Arrays, Linked Lists, Trees)",
        "Master basic sorting and search algorithms (QuickSort, Binary Search)",
        "Learn how HTTP protocols work, including headers, cookies, and status codes",
        "Understand basics of Docker containers and containerization benefits",
        "Learn basic commands of Linux/Unix operating systems and shell script",
        "Master SQL query composition, including joins, aggregations, and subqueries",
        "Learn basics of cloud service models (IaaS, PaaS, SaaS) and AWS",
        "Understand clean code concepts and code refactoring methods",
        "Learn core concepts of unit testing frameworks like JUnit/Jest",
        "Master NoSQL database paradigms and document storage (MongoDB/Firestore)",
        "Learn basics of system design, load balancers, and caching nodes",
        "Understand message brokers and event messaging patterns (Kafka/RabbitMQ)",
        "Learn CI/CD concepts and Jenkins/GitHub Actions pipelines",
        "Master advanced database patterns like transaction levels and indexing",
        "Learn how WebSockets operate for real-time network sync",
        "Understand security authentication standards like OAuth2 and OpenID",
        "Learn serverless architecture and cloud function execution models",
        "Master frontend optimization tricks like lazy imports and bundling",
        "Learn how search indices operate and how to implement Elasticsearch",
        "Understand microservices patterns, API gateways, and service registries",
        "Learn basic concepts of cryptography, hashing, and encryption",
        "Master memory management, garbage collection tuning, and profile tools",
        "Learn how GraphQL queries differ from traditional REST architectures",
        "Understand progressive web application (PWA) specifications",
        "Learn server-side rendering (SSR) frameworks like Next.js/Nuxt.js",
        "Master cloud design patterns like circuit breakers and bulkheads",
        "Learn container orchestration platforms (Kubernetes fundamentals)",
        "Understand infrastructure as code tools (Terraform/CloudFormation)",
        "Learn logging and visualization suites (ELK Stack/Prometheus)",
        "Master API testing automation using Postman runner collections",
        "Learn performance diagnostic tools for browser rendering cycles",
        "Understand functional programming patterns in Java and JavaScript",
        "Learn system integration strategies using message queues",
        "Master shell configuration and command line automation workflows",
        "Learn multi-threading constructs and concurrency controls",
        "Understand compiler optimization steps and byte execution paths",
        "Learn REST API versioning guidelines and deprecation policies",
        "Master database replication architectures and sharding patterns",
        "Learn responsive UI design practices for mobile-first web pages",
        "Understand web security defense systems like content security policies",
        "Learn API documentation languages (OpenAPI/Swagger specs)"
    );

    public static final List<String> PROJECTS = Arrays.asList(
        "Build a Personal Portfolio Website using responsive HTML/CSS/JS",
        "Create a Task Management System with user login and tasks database",
        "Develop an E-commerce Cart page with state-driven checkout features",
        "Build a Weather Dashboard API client displaying live metrics graphs",
        "Construct a Chat Application using WebSockets for real-time communication",
        "Create a Blog Management Platform with markdown writing tools",
        "Develop a Library Catalog System with search filters and checkout logs",
        "Build a Social Media Feed prototype with post creation and likes tracking",
        "Create an Expense Tracker Dashboard with interactive charts showing spend",
        "Develop a Recipe Finder Engine querying external food APIs",
        "Build a Student Grade Calculator with database logging endpoints",
        "Create a URL Shortener Service with redirection counters",
        "Develop an Online Survey Tool with dynamic fields generation",
        "Build a Fitness Progress Tracker with custom goal updates",
        "Create a Note-Taking App with offline sync features",
        "Develop a Simple Quiz Game with leaderboards and score logging",
        "Build a File Upload Sandbox linked with cloud storage components",
        "Create a Event Booking Portal with ticket generation features",
        "Develop a Movie Review Platform with user rating profiles",
        "Build an API Rate Limiter middleware as a utility plugin",
        "Create a Real-time Collaborative Notepad using shared document syncing",
        "Develop a E-learning Course Builder with video playlist players",
        "Build a Crypto Tracker detailing live coin price changes",
        "Create a Customer Relationship Manager (CRM) database module",
        "Develop a Hotel Reservation API with room availability checklists",
        "Build a Dockerized Microservice stack with API gateway routing",
        "Create a Resume Builder PDF generator from structured forms",
        "Develop an Employee Time Clock logging tool with geo-location entries",
        "Build a Customizable Markdown Editor with instant preview panel",
        "Create an Analytics Dashboard showing server resource metrics",
        "Develop a Job Search Portal with candidate registry options",
        "Build a Music Stream Player with play queue controls",
        "Create a Budget Splitter App with invoice scan OCR prototypes",
        "Develop a Real estate Catalog with map location overlays",
        "Build a Custom Package Manager for basic JavaScript utility files",
        "Create an Inventory Management DB with automated reorder triggers",
        "Develop a Flashcard App with spaced repetition algorithms",
        "Build a Dynamic Form Builder exporting schema templates",
        "Create a Security Sandbox testing API vulnerabilities interactively",
        "Develop a System Monitor dashboard showcasing process memory trends",
        "Build a Serverless Image Resizer triggered by upload queues",
        "Create a Custom CLI tool to automate project setup steps",
        "Develop a Quiz Bot for Slack/Discord channels with scoring",
        "Build a Web Scraper pipeline feeding a structured DB table",
        "Create a Multi-tenant Scheduling Calendar for doctor appointments",
        "Develop a Voting App using cryptographic validation steps",
        "Build a Distributed Lock service using database markers",
        "Create a Custom URL Status Ping utility with dashboard graphs",
        "Develop an Expense Splitter using complex matrix calculators",
        "Build a Code Editor playground rendering HTML codes instantly",
        "Create a Custom API Gateway handling header modifications",
        "Develop a Feedback Portal with sentiment analysis tags"
    );

    public static final List<String> CERTIFICATIONS = Arrays.asList(
        "AWS Certified Cloud Practitioner (Foundational)",
        "Google Cloud Digital Leader (Foundational)",
        "Microsoft Certified: Azure Fundamentals (AZ-900)",
        "Oracle Certified Associate, Java SE Programmer",
        "MongoDB Certified Developer Associate",
        "HashiCorp Certified: Terraform Associate",
        "Certified Kubernetes Application Developer (CKAD)",
        "AWS Certified Developer - Associate",
        "Google Cloud Associate Cloud Engineer",
        "Microsoft Certified: Azure Developer Associate (AZ-204)",
        "CompTIA Security+ Certification",
        "Scrum Alliance Certified ScrumMaster (CSM)",
        "Oracle Certified Professional, Java SE Developer",
        "Docker Certified Associate (DCA)",
        "Salesforce Certified Associate",
        "Python Institute Certified Associate in Python Programming (PCAP)",
        "Cisco Certified Network Associate (CCNA)",
        "Red Hat Certified System Administrator (RHCSA)",
        "IBM Cloud Certified Application Developer",
        "AWS Certified Solutions Architect - Associate",
        "Google Cloud Professional Cloud Architect",
        "Microsoft Certified: Azure Solutions Architect Expert",
        "Certified Information Systems Security Professional (CISSP)",
        "AWS Certified DevOps Engineer - Professional",
        "Google Cloud Professional DevOps Engineer",
        "Certified Information Security Manager (CISM)",
        "PMI Project Management Professional (PMP)",
        "Offensive Security Certified Professional (OSCP)",
        "CompTIA Network+ Certification",
        "Linux Foundation Certified System Administrator (LFCS)",
        "GitLab Certified Associate",
        "Spring Certified Professional",
        "GitHub Actions Certification",
        "Postman API First Apprentice Badge",
        "FreeCodeCamp Responsive Web Design Certificate",
        "HackerRank Problem Solving (Problem Solving Basic)",
        "HackerRank Java (Basic/Intermediate) Badge",
        "HackerRank SQL (Basic/Intermediate) Badge",
        "Udemy Full Stack Web Developer bootcamp completion",
        "Coursera Algorithmic Toolbox course certification",
        "edX Software Engineering Methods certificate",
        "Salesforce Certified Platform Developer I",
        "Certified Information Systems Auditor (CISA)",
        "CompTIA A+ Certification",
        "AWS Certified SysOps Administrator - Associate",
        "Oracle Certified Professional: Java EE Application Developer",
        "C++ Certified Professional Programmer (CPP)",
        "Microsoft Certified: Power BI Data Analyst Associate",
        "GIAC Security Essentials Certification (GSEC)",
        "Certified Scrum Product Owner (CSPO)",
        "Kubernetes and Cloud Native Associate (KCNA)",
        "AWS Certified Security - Specialty"
    );
}
